### ISSUE TITLE
Potential Malware Warning - Installation instructions section contains highly questionable link

### ISSUE THREAD

**Issue by charliemb2** [antoniotejada/Trilium-SyntaxHighlightWidget#18]
There is what many would consider a highly questionable link in the installation instructions for this widget.   Similar tactics have been used by hackers for other malware attempts on Github including some on Trilium's own Github page.  See the block below pointing to unreadable code at Cloudflare.  Specifically, see the line for "_Attach the highlight.min.js_." It's already a red flag that the `highlight.min.js` code is not on GitHub.  Add to that, it looks unstructured and hard to read, even in VSCode.  There would be little motivation that I can see for obscuring code like this unless it is malware.

Please check it and acknowledge here so that I may proceed with the installation.  Of course it could be legitimate and it looks like your code is `SyntaxHighlightWidget.js` while relying on `highlight.min.js`.

``` HTML
Installation
    Create a code note of type JS Frontend with the contents of SyntaxHighlightWidget.js and the label #widget
    Attach the [highlight.min.js](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js) file to that note
    To enable debug output, set the code note #debugLevel attribute to one of error, warn, info, log, debug (default is info)
```
P.S. If it turns out to be legitimate, I think it would be a good idea to add a footnote stating that the link to `highlight.min.js` is at Cloudflare, not Github, and contains unreadable compacted code.

**Comment by antoniotejada** [comment]
Nonsense, closing.
