### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by Sod-Almighty** [antoniotejada/Trilium-SyntaxHighlightWidget#8]
The plugin doesn't seem to be working. Am I doing something wrong?

I pasted the JS into a note, and attached the other JS as a binary file (as opposed to a text note). I reloaded the UI. Do I need to do something else? Thanks.

---

![Syntax Highlighting - Trilium Notes trilium, Today at 10 37 26 am](https://user-images.githubusercontent.com/4511095/188418633-9df9f6f8-310e-42a9-85dd-3ba068a22b89.png)

---

![highlight min js - Trilium Notes trilium, Today at 10 38 13 am](https://user-images.githubusercontent.com/4511095/188418785-d134412a-87c1-4825-b351-5c6daded86bc.png)

---

![highlight min js - Trilium Notes trilium, Today at 10 39 09 am](https://user-images.githubusercontent.com/4511095/188418970-04c9946a-3986-4a01-8b35-4dd8dddbac48.png)

**Comment by jph** [comment]
When I installed it, I simply dragged highlight.min.js onto the note I created as per the instructions and reloaded the page. Maybe try that and see how you go.

**Comment by antoniotejada** [comment]
@Sod-Almighty 

So yeah, what @jph said, I haven't tried recent Trilium versions, but it's just following the instructions, you can drag or you can `import file`, same thing. 

Didn't see anything wrong in your snapshots, make sure the syntax highlighting widget has the `#widget` label (`owned attributes`) and that you choose a language other than `plain text` so language autodetect kicks in.

There are a few closed issues of people who were failing to install it properly, check them to see if you find what you could missing.

**Comment by Sod-Almighty** [comment]
Apparently it was the `#widget` label. Which I don't recall being mentioned in your instructions...?

It's working now; but not brilliantly. Maybe it's detecting the wrong language? (Should be Julia.)

![Iteration - Trilium Notes trilium, Today at 11 36 04 am](https://user-images.githubusercontent.com/4511095/188614268-f9836eec-75bd-4ccc-a759-7b90990a1c80.png)

I would expect `for`, `in` and `end` to be highlighted. I would expect variables and random classes _not_ to be highlighted.

![Globals - Trilium Notes trilium, Today at 11 38 29 am](https://user-images.githubusercontent.com/4511095/188614703-e5a27cba-0715-468f-9bca-d5e72e1439c9.png)

Also anything after a `#` to be a comment, and coloured green.

![Indexing - Trilium Notes trilium, Today at 11 40 18 am](https://user-images.githubusercontent.com/4511095/188615026-b6647ba4-4c44-4623-b4a7-3e56e84edd09.png)

In addition, "to" should not be highlighted in the text of a printed exception. I figure this could be specified as "in a code block containing `julia>` at the start of at least one line, lines beginning `ERROR:` should be highlighted entirely in red".

**Comment by antoniotejada** [comment]
![image](https://user-images.githubusercontent.com/6446344/188715749-61b2f0d0-308d-454a-a2c8-28e3051436f9.png)

Closing.

**Comment by Sod-Almighty** [comment]
Okay, so the instructions did mention the label.

What about the fact that the damn thing doesn't highlight properly? We're all just gonna ignore that and close the ticket?

**Comment by jph** [comment]
> Okay, so the instructions did mention the label.
> 
> What about the fact that the damn thing doesn't highlight properly? We're all just gonna ignore that and close the ticket?

I think that may be a question for the highlightjs team, as the plugin itself appears to be working, but the highlighting isn't operational your expectation.
